apiVersion: v1
entries:
  common-app-chart:
  - apiVersion: v1
    appVersion: 4.1.0
    created: "2025-10-13T18:23:00.991689173+05:00"
    description: common-app-chart
    digest: 09f837f021837ef830efcddcb43fcbfb0811db179f6116af15e248207c682f63
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.1.0.tgz
    version: 4.1.0
  - apiVersion: v1
    appVersion: 4.0.9
    created: "2025-10-13T18:23:00.985498725+05:00"
    description: common-app-chart
    digest: 253a8ee2a9143333aa42f385c0d9e0746b2cd4b6ae84f5ef4bbcf8125a2533a2
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.9.tgz
    version: 4.0.9
  - apiVersion: v1
    appVersion: 4.0.8
    created: "2025-10-13T18:23:00.978716036+05:00"
    description: common-app-chart
    digest: d00114c7aa5ff6092f6e84eaae300b40bd02526725fd9f423b82e02a6251a6e4
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.8.tgz
    version: 4.0.8
  - apiVersion: v1
    appVersion: 4.0.7
    created: "2025-10-13T18:23:00.972474555+05:00"
    description: common-app-chart
    digest: ef5090a0993b85c4f428547b7f6cc3f3e7982d77090a09727fd8c704d17c8d1e
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.7.tgz
    version: 4.0.7
  - apiVersion: v1
    appVersion: 4.0.6
    created: "2025-10-13T18:23:00.964832416+05:00"
    description: common-app-chart
    digest: 036a97fa70729235c5ccc93ce4ed565c10f570600f78e529c85959e0e424720d
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.6.tgz
    version: 4.0.6
  - apiVersion: v1
    appVersion: 4.0.5
    created: "2025-10-13T18:23:00.955577534+05:00"
    description: common-app-chart
    digest: 77d123730f5ccb747cd5b5d07e6c7c86175a7dbcc262cdc12fc6a9065dbe2f36
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.5.tgz
    version: 4.0.5
  - apiVersion: v1
    appVersion: 4.0.4
    created: "2025-10-13T18:23:00.948602617+05:00"
    description: common-app-chart
    digest: aaedb71f8305f988d9e17971a09c88d79d7a4d11cfb7d63bc9ff3efa01e20f83
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.4.tgz
    version: 4.0.4
  - apiVersion: v1
    appVersion: 4.0.3
    created: "2025-10-13T18:23:00.942134136+05:00"
    description: common-app-chart
    digest: 32c79e47f042bc7e7b774da8ab786b46e60cf973f35c8ee2bbe77ccd576ec6c9
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.3.tgz
    version: 4.0.3
  - apiVersion: v1
    appVersion: 4.0.2
    created: "2025-10-13T18:23:00.936257884+05:00"
    description: common-app-chart
    digest: 299c0811bc8559fb184b6d455a86b1dc817ffdc6b20620764e3e69dc2f3619a9
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.2.tgz
    version: 4.0.2
  - apiVersion: v1
    appVersion: 4.0.1
    created: "2025-10-13T18:23:00.930350538+05:00"
    description: common-app-chart
    digest: 79e4290b4e786d54a33c19d65143f28f162195493d9de3ea5ccce7b388d2b82d
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.1.tgz
    version: 4.0.1
  - apiVersion: v1
    appVersion: 4.0.0
    created: "2025-10-13T18:23:00.924381308+05:00"
    description: common-app-chart
    digest: 30378aa76615e052197860a5989351d5de3e2be156d0db293a5ceb520c840e3a
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-4.0.0.tgz
    version: 4.0.0
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-10-13T18:23:00.918310231+05:00"
    description: common-app-chart
    digest: 113ec8c9ebe97993853e4acd7e4a0339f5f387c0046bfd0dc95622753fb7a88f
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v1
    appVersion: 3.0.1
    created: "2025-10-13T18:23:00.908692563+05:00"
    description: common-app-chart
    digest: ffa5a915ef88bdc42e16b35c50af3acef8a068df2a9a5e1ced8c47f338402f1e
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2025-10-13T18:23:00.902286036+05:00"
    description: common-app-chart
    digest: c1d9b84529aff74a0ccef9312ca590cf804f7e7faec5711f9cd6cd6fd2f6ac8d
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    appVersion: 2.4.0
    created: "2025-10-13T18:23:00.896563287+05:00"
    description: common-app-chart
    digest: 5a1b0193912632dc505faabce2255cb77aafa322385d458b2e9d25f4e9c216a5
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v1
    appVersion: 2.3.0
    created: "2025-10-13T18:23:00.891723737+05:00"
    description: common-app-chart
    digest: 3a2570680ec2ea21651dcaaf6781f07bce13c47f467bbcbd4695f4da79b7fc24
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2025-10-13T18:23:00.8860198+05:00"
    description: common-app-chart
    digest: ea8b15a62204dda988c6fc355d984e26ba60e23731a142e1ae1b21c0cb1b6eec
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2025-10-13T18:23:00.881412591+05:00"
    description: common-app-chart
    digest: 5f7d717f758dd5ec620a217459d2a6aabccc1fea416b889548769c39e0626b0c
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2025-10-13T18:23:00.877944698+05:00"
    description: common-app-chart
    digest: 87f9e32be94f1f9088061bd20d4bd3a4f97a4874d3fe15a8fa79ad1f1b7b9a31
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 1.0.5
    created: "2025-10-13T18:23:00.874612168+05:00"
    description: common-app-chart
    digest: 50cd46f994f1d4a9385002251d8329c817ad1ebf04813f1eeb76eb11f46b1434
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v1
    appVersion: 1.0.4
    created: "2025-10-13T18:23:00.871151144+05:00"
    description: common-app-chart
    digest: 0cd4e7e97c2b1cb13a21ae57fbbaa0118ac276b1f66fa6e153294b325aee0782
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    appVersion: 1.0.3
    created: "2025-10-13T18:23:00.868000525+05:00"
    description: common-app-chart
    digest: 3c2fa9650c1b4e5cf55d5070d7c06defe319348695670710771ccd2bdf8e59f7
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: 1.0.2
    created: "2025-10-13T18:23:00.862783932+05:00"
    description: common-app-chart
    digest: 993ce0bc0470ab92f74fbc148ac3e7811e7f1a901f3084c301f5377e78dddaa7
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 1.0.1
    created: "2025-10-13T18:23:00.857551129+05:00"
    description: common-app-chart
    digest: 3cacec2448a27f7bfe48750a786b0b0a0560dd5f514ecc88d225869ece687576
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2025-10-13T18:23:00.853983129+05:00"
    description: common-app-chart
    digest: 03c515abc217d4b7eaf2bccb1a15eece6276afd41f54c6d61c735615cd031ee8
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: common-app-chart
    urls:
    - common-app-chart-1.0.0.tgz
    version: 1.0.0
generated: "2025-10-13T18:23:00.848428985+05:00"
